#./act.exe -W .github/workflows/deploy-stage.yml
name: Build
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "norookezi/kakeibo_app"
          type: "stable"

      - name: Check connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            echo "SSH Connection Successful"

      - name: Download last release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            curl -L https://codeload.github.com/Norookezi/kakeibo_app/tar.gz/refs/tags/${{ steps.node_release.outputs.release }} -o /home/git/${{ steps.node_release.outputs.release }}.tar.gz

      - name: Replace the previous prod release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            cd /home/git
            rm -rf ./kakeibo_app/*
            tar -xvzf ./${{ steps.node_release.outputs.release }}.tar.gz --strip-components=1 -C ./kakeibo_app/
