#./act.exe -W .github/workflows/deploy-stage.yml
name: Build
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "norookezi/kakeibo_app"
          type: "stable"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_PASSWORD: ${{ secrets.PASSWORD }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Dump GitHub context
        #run: ssh staging 'curl -L https://codeload.github.com/Norookezi/kakeibo_app/tar.gz/refs/tags/v10.0.0 -o /home/git/v10.0.0.tar.gz'
        run: ssh staging 'echo "${{ steps.node_release.outputs.release }}" > /home/git/v10.0.0.txt'
