name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Pull Latest Code
      run: |
        git pull

    - name: Test
      run: |
        ls

    - name: Install dependencies
      run: |
        npm ci

    - name: Build Project
      run: |
        npm run build